environment:
  HEADERSURL: ${HEADERSURL}
packages:
  - name: serverless-autoip
    actions:
      - name: noip
        limits:
          timeout: 180000
          memory: 1024
        runtime: 'python:default'